// generate-emojis.mjs — the full emoji vocabulary, generated at dev time.
//
// KP's ruling (2026-07-31, verbatim on the geode `hearth` node §⑥a): "we
// want to load the hearth with a full set of options otherwise we limit
// its vessel to what we chose." So: the WHOLE Unicode set, no curation.
// This script fetches Unicode's own emoji-test.txt (dev environment only —
// the shipped app makes no network calls, ever) and emits
// src/lib/data/emojis.gen.ts: generated, never hand-edited, healed by
// regeneration (the house's GAIA law at emoji scale).
//
//   node scripts/generate-emojis.mjs
//
// What it keeps: every fully-qualified emoji, its Unicode name, and its
// group. What it sets aside: the Component group (skin-tone/hair swatches
// that are not emojis on their own) and minimally-/unqualified duplicates
// of the same emoji. Meaning is deliberately NOT shipped: names are for
// SEARCH, never definitions — the vessel brings the meaning.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://unicode.org/Public/emoji/latest/emoji-test.txt';
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'data', 'emojis.gen.ts');

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`emoji-test.txt answered ${res.status} — nothing was written.`);
const text = await res.text();

const versionLine = text.split('\n').find((l) => l.startsWith('# Version:'))?.trim() ?? '# Version: unknown';

let group = '';
const groups = [];
const byGroup = new Map();
let kept = 0;
let setAside = 0;

for (const line of text.split('\n')) {
	if (line.startsWith('# group:')) {
		group = line.slice('# group:'.length).trim();
		continue;
	}
	if (!line || line.startsWith('#')) continue;
	// 1F600 ; fully-qualified # 😀 E1.0 grinning face
	const m = line.match(/^([0-9A-F ]+);\s*(\S+)\s*#\s*(\S+)\s+E[\d.]+\s+(.+)$/);
	if (!m) continue;
	const [, , status, emoji, name] = m;
	if (status !== 'fully-qualified' || group === 'Component') {
		setAside++;
		continue;
	}
	if (!byGroup.has(group)) {
		byGroup.set(group, []);
		groups.push(group);
	}
	byGroup.get(group).push({ e: emoji, n: name });
	kept++;
}

if (kept < 3000) throw new Error(`Only ${kept} emoji parsed — the source shape may have shifted; nothing was written.`);

const lines = [];
lines.push('// GENERATED by scripts/generate-emojis.mjs — never hand-edit; heal by regenerating.');
lines.push(`// Source: ${SOURCE} (${versionLine.replace('# ', '')})`);
lines.push(`// ${kept} fully-qualified emoji in ${groups.length} groups; ${setAside} component/duplicate forms set aside.`);
lines.push('// Names are for search only — meaning is the vessel\'s own (KP\'s ruling, 2026-07-31).');
lines.push('');
lines.push('export interface EmojiEntry {');
lines.push('\t/** the emoji itself */ e: string;');
lines.push('\t/** its Unicode name — a search key, never a definition */ n: string;');
lines.push('}');
lines.push('');
lines.push('export const EMOJI_GROUPS: { group: string; emojis: EmojiEntry[] }[] = [');
for (const g of groups) {
	lines.push(`\t{ group: ${JSON.stringify(g)}, emojis: [`);
	for (const { e, n } of byGroup.get(g)) {
		lines.push(`\t\t{ e: ${JSON.stringify(e)}, n: ${JSON.stringify(n)} },`);
	}
	lines.push('\t] },');
}
lines.push('];');
lines.push('');
lines.push('export const EMOJI_COUNT = ' + kept + ';');
lines.push('');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`emojis.gen.ts written: ${kept} emoji, ${groups.length} groups (${setAside} forms set aside).`);
